# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21c054f9ff551dd72816dc3166297e4e17f770855718ee6faf466992610281b298f7e7856feae11183fbc01c06aafb4eef5ea1731f7a4a02f2a3c6ee88b8615

test:
  secret_key_base: 1a5b61befed3e0eea4173e0bcb6e4533fd14ffbc3fcbec22833094e7b222b9133cc7b776d1d4b82aa660dfa5fdd3456762459df846d966ec1645bc60295070f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
